// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cwbylvncmgumxoskpjvm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3Ynlsdm5jbWd1bXhvc2twanZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNzMwMTYsImV4cCI6MjA2NDY0OTAxNn0.FcaCwG3TDSYeic8mNFrEygiYxxOkNVBk_beEvxuoivU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);